ejer2.4: Temperatura.o
	c++ ejer2.4.cpp Temperatura.o -o ejer2.4

ejer2.5: Fraccion.o
	c++ ejer2.5.cpp Fraccion.o -o ejer2.5

Temperatura.o: Temperatura.h
	c++ Temperatura.cpp -c

Fraccion.o: Fraccion.h
	c++ Fraccion.cpp -c

Clean:
	rm *.o
